ARG PYTHON_VERSION=3.11.1
FROM python:${PYTHON_VERSION}-slim

RUN pip install --upgrade pip \
    && pip install pip-tools

# The line below will get added to the top of "requirements.txt"
ENV CUSTOM_COMPILE_COMMAND="make reqs"
