name: Update release version
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0

      - name: Get version from tags
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      - name: Perform lint
        run: make lint

      - name: Perform dist
        env:
          PBR_VERSION: ${{ steps.tag_version.outputs.new_version }}
        run: make dist

      - name: Perform tests
        env:
          PBR_VERSION: ${{ steps.tag_version.outputs.new_version }}
        run: make test

      - name: Test pip package installation.
        run: make installcheck

      - name: Add GitHub tag and release
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
